chore : test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,4 +38,9 @@ jobs:
           HOST: ${{ vars.HOST }}
           USER: ${{ vars.USER }}
         run: |
-          ssh -vvv -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $USER@$HOST "echo 'Successfully connected to the server'; exit" || echo "SSH Exit Code: $?"
+          ssh -vvv -o StrictHostKeyChecking=no -i $SSH_PRIVATE_KEY $USER@$HOST "echo 'Successfully connected to the server';     if [ $? -eq 0 ]; then
+            echo "SSH Connection successful"
+          else
+            echo "SSH Connection failed"
+            exit 1
+          fi
